image: maven:3.8.4-openjdk-17

stages:
  - build
  - test
  - deploy

mybuild:
  stage: build
  script: mvn compile

mytest:
  stage: test
  script: mvn test

mydeploy:
  stage: deploy
  script: mvn deploy