<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>src.main</groupId>
    <artifactId>backend</artifactId>
    <version>0.0.1</version>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M6</version>
            </plugin>
        </plugins>
    </build>
</project>